export type AlphabetItem = {
  letter: string;
  upper: string;
  lower: string;
  word: string;
  image: string;
  audio: string;
  worksheet: string;
  sentence: string;
};

export const alphabetItems: AlphabetItem[] = [
  {
    letter: "a",
    upper: "A",
    lower: "a",
    word: "apple",
    image: "/alphabet/a.png",
    audio: "/audio/alphabet/Aa.m4a",
    worksheet: "/worksheets/alphabet/Aa.hwp",
    sentence: 'This is the letter A, pronounced as "a".',
  },
  {
    letter: "b",
    upper: "B",
    lower: "b",
    word: "ball",
    image: "/alphabet/b.png",
    audio: "/audio/alphabet/Bb.m4a",
    worksheet: "/worksheets/alphabet/Bb.hwp",
    sentence: 'This is the letter B, pronounced as "b".',
  },
  {
    letter: "c",
    upper: "C",
    lower: "c",
    word: "cat",
    image: "/alphabet/c.png",
    audio: "/audio/alphabet/Cc.m4a",
    worksheet: "/worksheets/alphabet/Cc.hwp",
    sentence: 'This is the letter C, pronounced as "c".',
  },
  {
    letter: "d",
    upper: "D",
    lower: "d",
    word: "dog",
    image: "/alphabet/d.png",
    audio: "/audio/alphabet/Dd.m4a",
    worksheet: "/worksheets/alphabet/Dd.hwp",
    sentence: 'This is the letter D, pronounced as "d".',
  },
  {
    letter: "e",
    upper: "E",
    lower: "e",
    word: "egg",
    image: "/alphabet/e.png",
    audio: "/audio/alphabet/Ee.m4a",
    worksheet: "/worksheets/alphabet/Ee.hwp",
    sentence: 'This is the letter E, pronounced as "e".',
  },
  {
    letter: "f",
    upper: "F",
    lower: "f",
    word: "fish",
    image: "/alphabet/f.png",
    audio: "/audio/alphabet/Ff.m4a",
    worksheet: "/worksheets/alphabet/Ff.hwp",
    sentence: 'This is the letter F, pronounced as "f".',
  },
  {
    letter: "g",
    upper: "G",
    lower: "g",
    word: "goat",
    image: "/alphabet/g.png",
    audio: "/audio/alphabet/Gg.m4a",
    worksheet: "/worksheets/alphabet/Gg.hwp",
    sentence: 'This is the letter G, pronounced as "g".',
  },
  {
    letter: "h",
    upper: "H",
    lower: "h",
    word: "hat",
    image: "/alphabet/h.png",
    audio: "/audio/alphabet/Hh.m4a",
    worksheet: "/worksheets/alphabet/Hh.hwp",
    sentence: 'This is the letter H, pronounced as "h".',
  },
  {
    letter: "i",
    upper: "I",
    lower: "i",
    word: "ink",
    image: "/alphabet/i.png",
    audio: "/audio/alphabet/Ii.m4a",
    worksheet: "/worksheets/alphabet/Ii.hwp",
    sentence: 'This is the letter I, pronounced as "i".',
  },
  {
    letter: "j",
    upper: "J",
    lower: "j",
    word: "jam",
    image: "/alphabet/j.png",
    audio: "/audio/alphabet/Jj.m4a",
    worksheet: "/worksheets/alphabet/Jj.hwp",
    sentence: 'This is the letter J, pronounced as "j".',
  },
  {
    letter: "k",
    upper: "K",
    lower: "k",
    word: "kite",
    image: "/alphabet/k.png",
    audio: "/audio/alphabet/Kk.m4a",
    worksheet: "/worksheets/alphabet/Kk.hwp",
    sentence: 'This is the letter K, pronounced as "k".',
  },
  {
    letter: "l",
    upper: "L",
    lower: "l",
    word: "lion",
    image: "/alphabet/l.png",
    audio: "/audio/alphabet/Ll.m4a",
    worksheet: "/worksheets/alphabet/Ll.hwp",
    sentence: 'This is the letter L, pronounced as "l".',
  },
  {
    letter: "m",
    upper: "M",
    lower: "m",
    word: "moon",
    image: "/alphabet/m.png",
    audio: "/audio/alphabet/Mm.m4a",
    worksheet: "/worksheets/alphabet/Mm.hwp",
    sentence: 'This is the letter M, pronounced as "m".',
  },
  {
    letter: "n",
    upper: "N",
    lower: "n",
    word: "nest",
    image: "/alphabet/n.png",
    audio: "/audio/alphabet/Nn.m4a",
    worksheet: "/worksheets/alphabet/Nn.hwp",
    sentence: 'This is the letter N, pronounced as "n".',
  },
  {
    letter: "o",
    upper: "O",
    lower: "o",
    word: "orange",
    image: "/alphabet/o.png",
    audio: "/audio/alphabet/Oo.m4a",
    worksheet: "/worksheets/alphabet/Oo.hwp",
    sentence: 'This is the letter O, pronounced as "o".',
  },
  {
    letter: "p",
    upper: "P",
    lower: "p",
    word: "pig",
    image: "/alphabet/p.png",
    audio: "/audio/alphabet/Pp.m4a",
    worksheet: "/worksheets/alphabet/Pp.hwp",
    sentence: 'This is the letter P, pronounced as "p".',
  },
  {
    letter: "q",
    upper: "Q",
    lower: "q",
    word: "queen",
    image: "/alphabet/q.png",
    audio: "/audio/alphabet/Qq.m4a",
    worksheet: "/worksheets/alphabet/Qq.hwp",
    sentence: 'This is the letter Q, pronounced as "q".',
  },
  {
    letter: "r",
    upper: "R",
    lower: "r",
    word: "rabbit",
    image: "/alphabet/r.png",
    audio: "/audio/alphabet/Rr.m4a",
    worksheet: "/worksheets/alphabet/Rr.hwp",
    sentence: 'This is the letter R, pronounced as "r".',
  },
  {
    letter: "s",
    upper: "S",
    lower: "s",
    word: "sun",
    image: "/alphabet/s.png",
    audio: "/audio/alphabet/Ss.m4a",
    worksheet: "/worksheets/alphabet/Ss.hwp",
    sentence: 'This is the letter S, pronounced as "s".',
  },
  {
    letter: "t",
    upper: "T",
    lower: "t",
    word: "tree",
    image: "/alphabet/t.png",
    audio: "/audio/alphabet/Tt.m4a",
    worksheet: "/worksheets/alphabet/Tt.hwp",
    sentence: 'This is the letter T, pronounced as "t".',
  },
  {
    letter: "u",
    upper: "U",
    lower: "u",
    word: "umbrella",
    image: "/alphabet/u.png",
    audio: "/audio/alphabet/Uu.m4a",
    worksheet: "/worksheets/alphabet/Uu.hwp",
    sentence: 'This is the letter U, pronounced as "u".',
  },
  {
    letter: "v",
    upper: "V",
    lower: "v",
    word: "van",
    image: "/alphabet/v.png",
    audio: "/audio/alphabet/Vv.m4a",
    worksheet: "/worksheets/alphabet/Vv.hwp",
    sentence: 'This is the letter V, pronounced as "v".',
  },
  {
    letter: "w",
    upper: "W",
    lower: "w",
    word: "watch",
    image: "/alphabet/w.png",
    audio: "/audio/alphabet/Ww.m4a",
    worksheet: "/worksheets/alphabet/Ww.hwp",
    sentence: 'This is the letter W, pronounced as "w".',
  },
  {
    letter: "x",
    upper: "X",
    lower: "x",
    word: "xylophone",
    image: "/alphabet/x.png",
    audio: "/audio/alphabet/Xx.m4a",
    worksheet: "/worksheets/alphabet/Xx.hwp",
    sentence: 'This is the letter X, pronounced as "x".',
  },
  {
    letter: "y",
    upper: "Y",
    lower: "y",
    word: "yoyo",
    image: "/alphabet/y.png",
    audio: "/audio/alphabet/Yy.m4a",
    worksheet: "/worksheets/alphabet/Yy.hwp",
    sentence: 'This is the letter Y, pronounced as "y".',
  },
  {
    letter: "z",
    upper: "Z",
    lower: "z",
    word: "zebra",
    image: "/alphabet/z.png",
    audio: "/audio/alphabet/Zz.m4a",
    worksheet: "/worksheets/alphabet/Zz.hwp",
    sentence: 'This is the letter Z, pronounced as "z".',
  },
];