// app/(main)/shop/data.ts

export type CategoryId =
  | "royal"
  | "job"
  | "student"
  | "family"
  | "battle"
  | "fantasy";

export type Category = {
  id: CategoryId;
  label: string;
  icon: string;
};

export type BunnySkin = {
  id: string;
  category: CategoryId;
  name: string;
  price: number;
  image: string;
  rarity: "Common" | "Rare" | "Epic" | "Legendary";
  description: string;
};

export type BackgroundSkin = {
  id: string;
  category: CategoryId;
  name: string;
  price: number;
  image: string;
  description: string;
};

export const categories: Category[] = [
  { id: "student", label: "학생", icon: "🎒" },
  { id: "royal", label: "왕실", icon: "👑" },
  { id: "job", label: "직업", icon: "💼" },
  { id: "family", label: "가족", icon: "🏡" },
  { id: "battle", label: "전투", icon: "⚔️" },
  { id: "fantasy", label: "판타지", icon: "✨" },
];

// 가격 기준 (2026-08-26, 최저 구매가 100코인부터 시작하도록 재조정)
// Common 100~120 / Rare 140~170 / Epic 180~210 / Legendary 230~250
export const bunnySkins: BunnySkin[] = [
  {
    id: "basic_bunny",
    category: "student",
    name: "Basic Bunny",
    price: 0,
    image: "/shop/bunny.png",
    rarity: "Common",
    description: "처음부터 함께하는 기본 토끼",
  },

  {
    id: "princess_bunny",
    category: "royal",
    name: "Princess Bunny",
    price: 140,
    image: "/shop/bunnies/royal/princess_bunny.png",
    rarity: "Rare",
    description: "분홍 드레스를 입은 공주 토끼",
  },
  {
    id: "prince_bunny",
    category: "royal",
    name: "Prince Bunny",
    price: 140,
    image: "/shop/bunnies/royal/prince_bunny.png",
    rarity: "Rare",
    description: "작은 왕관을 쓴 왕자 토끼",
  },
  {
    id: "queen_bunny",
    category: "royal",
    name: "Queen Bunny",
    price: 180,
    image: "/shop/bunnies/royal/queen_bunny.png",
    rarity: "Epic",
    description: "우아한 망토를 두른 여왕 토끼",
  },
  {
    id: "king_bunny",
    category: "royal",
    name: "King Bunny",
    price: 180,
    image: "/shop/bunnies/royal/king_bunny.png",
    rarity: "Epic",
    description: "황금 왕관을 쓴 왕 토끼",
  },
  {
    id: "tea_party_bunny",
    category: "royal",
    name: "Tea Party Bunny",
    price: 150,
    image: "/shop/bunnies/royal/tea_party_bunny.png",
    rarity: "Rare",
    description: "왕실 티파티에 초대된 토끼",
  },
  {
    id: "royal_guard_bunny",
    category: "royal",
    name: "Royal Guard Bunny",
    price: 200,
    image: "/shop/bunnies/royal/royal_guard_bunny.png",
    rarity: "Epic",
    description: "궁전을 지키는 근위병 토끼",
  },

  {
    id: "chef_bunny",
    category: "job",
    name: "Chef Bunny",
    price: 120,
    image: "/shop/bunnies/job/chef_bunny.png",
    rarity: "Common",
    description: "맛있는 당근 요리를 만드는 토끼",
  },
  {
    id: "doctor_bunny",
    category: "job",
    name: "Doctor Bunny",
    price: 150,
    image: "/shop/bunnies/job/doctor_bunny.png",
    rarity: "Rare",
    description: "친구들을 돌봐주는 의사 토끼",
  },
  {
    id: "teacher_bunny",
    category: "job",
    name: "Teacher Bunny",
    price: 140,
    image: "/shop/bunnies/job/teacher_bunny.png",
    rarity: "Rare",
    description: "알파벳을 알려주는 선생님 토끼",
  },
  {
    id: "police_bunny",
    category: "job",
    name: "Police Bunny",
    price: 150,
    image: "/shop/bunnies/job/police_bunny.png",
    rarity: "Rare",
    description: "마을의 안전을 지키는 경찰 토끼",
  },
  {
    id: "artist_bunny",
    category: "job",
    name: "Artist Bunny",
    price: 140,
    image: "/shop/bunnies/job/artist_bunny.png",
    rarity: "Rare",
    description: "색연필과 붓을 든 예술가 토끼",
  },
  {
    id: "pilot_bunny",
    category: "job",
    name: "Pilot Bunny",
    price: 190,
    image: "/shop/bunnies/job/pilot_bunny.png",
    rarity: "Epic",
    description: "하늘을 나는 조종사 토끼",
  },

  {
    id: "university_bunny",
    category: "student",
    name: "University Bunny",
    price: 110,
    image: "/shop/bunnies/student/university_bunny.png",
    rarity: "Common",
    description: "멋진 대학생 토끼",
  },
  {
    id: "kindergarten_bunny",
    category: "student",
    name: "Kindergarten Bunny",
    price: 100,
    image: "/shop/bunnies/student/kindergarten_bunny.png",
    rarity: "Common",
    description: "노란 모자를 쓴 유치원 토끼",
  },
  {
    id: "athlete_bunny",
    category: "student",
    name: "Athlete Bunny",
    price: 120,
    image: "/shop/bunnies/student/athlete_bunny.png",
    rarity: "Common",
    description: "늘 활기찬 운동부 토끼",
  },
  {
    id: "library_bunny",
    category: "student",
    name: "Library Bunny",
    price: 140,
    image: "/shop/bunnies/student/library_bunny.png",
    rarity: "Rare",
    description: "조용히 책을 읽는 도서관 토끼",
  },
  {
    id: "music_bunny",
    category: "student",
    name: "Music Bunny",
    price: 150,
    image: "/shop/bunnies/student/music_bunny.png",
    rarity: "Rare",
    description: "음악 시간에 노래하는 토끼",
  },
  {
    id: "graduation_bunny",
    category: "student",
    name: "Graduation Bunny",
    price: 200,
    image: "/shop/bunnies/student/graduation_bunny.png",
    rarity: "Epic",
    description: "졸업 가운을 입은 토끼",
  },

  {
    id: "mom_bunny",
    category: "family",
    name: "Mom Bunny",
    price: 120,
    image: "/shop/bunnies/family/mom_bunny.png",
    rarity: "Common",
    description: "앞치마를 입은 따뜻한 엄마 토끼",
  },
  {
    id: "dad_bunny",
    category: "family",
    name: "Dad Bunny",
    price: 120,
    image: "/shop/bunnies/family/dad_bunny.png",
    rarity: "Common",
    description: "넥타이를 맨 아빠 토끼",
  },
  {
    id: "baby_bunny",
    category: "family",
    name: "Baby Bunny",
    price: 110,
    image: "/shop/bunnies/family/baby_bunny.png",
    rarity: "Common",
    description: "턱받이를 한 아기 토끼",
  },
  {
    id: "sibling_bunny",
    category: "family",
    name: "Sibling Bunny",
    price: 140,
    image: "/shop/bunnies/family/sibling_bunny.png",
    rarity: "Rare",
    description: "친구 같은 형제 토끼",
  },
  {
    id: "grandma_bunny",
    category: "family",
    name: "Grandma Bunny",
    price: 150,
    image: "/shop/bunnies/family/grandma_bunny.png",
    rarity: "Rare",
    description: "언제나 다정한 할머니 토끼",
  },
  {
    id: "grandpa_bunny",
    category: "family",
    name: "Grandpa Bunny",
    price: 150,
    image: "/shop/bunnies/family/grandpa_bunny.png",
    rarity: "Rare",
    description: "따스한 눈빛의 할아버지 토끼",
  },

  {
    id: "knight_bunny",
    category: "battle",
    name: "Knight Bunny",
    price: 180,
    image: "/shop/bunnies/battle/knight_bunny.png",
    rarity: "Epic",
    description: "은빛 갑옷을 입은 기사 토끼",
  },
  {
    id: "archer_bunny",
    category: "battle",
    name: "Archer Bunny",
    price: 160,
    image: "/shop/bunnies/battle/archer_bunny.png",
    rarity: "Rare",
    description: "활을 든 숲속 궁수 토끼",
  },
  {
    id: "hero_bunny",
    category: "battle",
    name: "Hero Bunny",
    price: 200,
    image: "/shop/bunnies/battle/hero_bunny.png",
    rarity: "Epic",
    description: "망토를 두른 용감한 히어로 토끼",
  },
  {
    id: "ninja_bunny",
    category: "battle",
    name: "Ninja Bunny",
    price: 190,
    image: "/shop/bunnies/battle/ninja_bunny.png",
    rarity: "Epic",
    description: "조용히 움직이는 닌자 토끼",
  },
  {
    id: "cavalry_bunny",
    category: "battle",
    name: "Cavalry Bunny",
    price: 170,
    image: "/shop/bunnies/battle/cavalry_bunny.png",
    rarity: "Rare",
    description: "용맹하게 싸우는 기마 토끼",
  },
  {
    id: "dragon_bunny",
    category: "battle",
    name: "Dragon Bunny",
    price: 250,
    image: "/shop/bunnies/battle/dragon_bunny.png",
    rarity: "Legendary",
    description: "용의 기운을 가진 전설 토끼",
  },

  {
    id: "wizard_bunny",
    category: "fantasy",
    name: "Wizard Bunny",
    price: 180,
    image: "/shop/bunnies/fantasy/wizard_bunny.png",
    rarity: "Epic",
    description: "별빛 지팡이를 든 마법사 토끼",
  },
  {
    id: "fairy_bunny",
    category: "fantasy",
    name: "Fairy Bunny",
    price: 190,
    image: "/shop/bunnies/fantasy/fairy_bunny.png",
    rarity: "Epic",
    description: "투명 날개를 가진 요정 토끼",
  },
  {
    id: "dwarf_bunny",
    category: "fantasy",
    name: "Dwarf Bunny",
    price: 230,
    image: "/shop/bunnies/fantasy/dwarf_bunny.png",
    rarity: "Legendary",
    description: "무엇이든 고칠 수 있는 드워프 토끼",
  },
  {
    id: "elf_bunny",
    category: "fantasy",
    name: "Elf Bunny",
    price: 200,
    image: "/shop/bunnies/fantasy/elf_bunny.png",
    rarity: "Epic",
    description: "모든 것을 사랑하는 엘프 토끼",
  },
  {
    id: "angel_bunny",
    category: "fantasy",
    name: "Angel Bunny",
    price: 210,
    image: "/shop/bunnies/fantasy/angel_bunny.png",
    rarity: "Epic",
    description: "작은 천사 날개를 가진 토끼",
  },
  {
    id: "dark_bunny",
    category: "fantasy",
    name: "Dark Bunny",
    price: 160,
    image: "/shop/bunnies/fantasy/dark_bunny.png",
    rarity: "Rare",
    description: "어둠의 마법을 사용하는 다크 토끼",
  },
];

export const backgroundSkins: BackgroundSkin[] = [
  {
    id: "default_bg",
    category: "student",
    name: "기본 옷장 배경",
    price: 0,
    image: "/shop/closet-bg.png",
    description: "처음부터 함께하는 기본 배경",
  },

  // ===== STUDENT =====
  {
    id: "student_classroom",
    category: "student",
    name: "교실 배경",
    price: 50,
    image: "/shop/backgrounds/student/classroom.png",
    description: "영어를 배우는 아늑한 교실",
  },
  {
    id: "student_university",
    category: "student",
    name: "대학 캠퍼스 배경",
    price: 50,
    image: "/shop/backgrounds/student/university.png",
    description: "책과 낭만이 있는 대학 캠퍼스",
  },
  {
    id: "student_kindergarten",
    category: "student",
    name: "유치원 놀이터 배경",
    price: 50,
    image: "/shop/backgrounds/student/kindergarten.png",
    description: "노란 모자 친구들이 뛰노는 유치원",
  },
  {
    id: "student_sports_field",
    category: "student",
    name: "운동장 배경",
    price: 50,
    image: "/shop/backgrounds/student/sports_field.png",
    description: "힘차게 뛰노는 활기찬 운동장",
  },
  {
    id: "student_library",
    category: "student",
    name: "도서관 배경",
    price: 50,
    image: "/shop/backgrounds/student/library.png",
    description: "책이 가득한 조용한 도서관",
  },
  {
    id: "student_music_room",
    category: "student",
    name: "음악실 배경",
    price: 50,
    image: "/shop/backgrounds/student/music_room.png",
    description: "노래와 악기 소리가 가득한 음악실",
  },
  {
    id: "student_graduation_hall",
    category: "student",
    name: "졸업식장 배경",
    price: 50,
    image: "/shop/backgrounds/student/graduation_hall.png",
    description: "꽃다발과 박수가 가득한 졸업식장",
  },

  // ===== ROYAL =====
  {
    id: "royal_palace",
    category: "royal",
    name: "왕실 배경",
    price: 60,
    image: "/shop/backgrounds/royal/palace.png",
    description: "화려한 궁전 속 왕실 분위기",
  },
  {
    id: "royal_princess_room",
    category: "royal",
    name: "공주의 방 배경",
    price: 60,
    image: "/shop/backgrounds/royal/princess_room.png",
    description: "분홍빛으로 물든 공주의 방",
  },
  {
    id: "royal_palace_courtyard",
    category: "royal",
    name: "궁전 정원 배경",
    price: 60,
    image: "/shop/backgrounds/royal/palace_courtyard.png",
    description: "햇살 가득한 궁전의 정원",
  },
  {
    id: "royal_throne_hall",
    category: "royal",
    name: "왕좌의 방 배경",
    price: 60,
    image: "/shop/backgrounds/royal/throne_hall.png",
    description: "위엄이 느껴지는 왕좌의 방",
  },
  {
    id: "royal_hall",
    category: "royal",
    name: "왕궁 홀 배경",
    price: 60,
    image: "/shop/backgrounds/royal/royal_hall.png",
    description: "황금빛으로 빛나는 왕궁의 홀",
  },
  {
    id: "royal_tea_garden",
    category: "royal",
    name: "티파티 정원 배경",
    price: 60,
    image: "/shop/backgrounds/royal/tea_garden.png",
    description: "우아한 티타임이 열리는 정원",
  },
  {
    id: "royal_palace_gate",
    category: "royal",
    name: "궁전 정문 배경",
    price: 60,
    image: "/shop/backgrounds/royal/palace_gate.png",
    description: "근위병이 지키는 궁전의 정문",
  },

  // ===== JOB =====
  {
    id: "job_town",
    category: "job",
    name: "직업 마을 배경",
    price: 50,
    image: "/shop/backgrounds/job/job_town.png",
    description: "다양한 직업이 모인 Job Town",
  },
  {
    id: "job_bakery",
    category: "job",
    name: "빵집 배경",
    price: 50,
    image: "/shop/backgrounds/job/bakery.png",
    description: "고소한 빵 냄새 가득한 빵집",
  },
  {
    id: "job_hospital",
    category: "job",
    name: "병원 배경",
    price: 50,
    image: "/shop/backgrounds/job/hospital.png",
    description: "친절한 의사 선생님이 있는 병원",
  },
  {
    id: "job_school",
    category: "job",
    name: "학교 교실 배경",
    price: 50,
    image: "/shop/backgrounds/job/school.png",
    description: "선생님이 수업하는 교실",
  },
  {
    id: "job_police_station",
    category: "job",
    name: "경찰서 배경",
    price: 50,
    image: "/shop/backgrounds/job/police_station.png",
    description: "마을을 지키는 든든한 경찰서",
  },
  {
    id: "job_art_studio",
    category: "job",
    name: "화실 배경",
    price: 50,
    image: "/shop/backgrounds/job/art_studio.png",
    description: "물감과 붓이 가득한 화실",
  },
  {
    id: "job_airport",
    category: "job",
    name: "공항 배경",
    price: 50,
    image: "/shop/backgrounds/job/airport.png",
    description: "하늘을 향해 날아오르는 공항",
  },

  // ===== FAMILY =====
  {
    id: "family_living_room",
    category: "family",
    name: "가족 거실 배경",
    price: 50,
    image: "/shop/backgrounds/family/living_room.png",
    description: "따뜻한 우리 가족의 거실",
  },
  {
    id: "family_kitchen",
    category: "family",
    name: "주방 배경",
    price: 50,
    image: "/shop/backgrounds/family/kitchen.png",
    description: "맛있는 요리가 가득한 주방",
  },
  {
    id: "family_garage",
    category: "family",
    name: "차고 배경",
    price: 50,
    image: "/shop/backgrounds/family/garage.png",
    description: "아빠의 손길이 담긴 차고",
  },
  {
    id: "family_nursery",
    category: "family",
    name: "아기방 배경",
    price: 50,
    image: "/shop/backgrounds/family/nursery.png",
    description: "포근한 아기의 방",
  },
  {
    id: "family_playroom",
    category: "family",
    name: "놀이방 배경",
    price: 50,
    image: "/shop/backgrounds/family/playroom.png",
    description: "형제자매가 함께 노는 놀이방",
  },
  {
    id: "family_grandma_garden",
    category: "family",
    name: "할머니 정원 배경",
    price: 50,
    image: "/shop/backgrounds/family/grandma_garden.png",
    description: "정겨운 할머니의 텃밭 정원",
  },
  {
    id: "family_grandpa_porch",
    category: "family",
    name: "할아버지 마루 배경",
    price: 50,
    image: "/shop/backgrounds/family/grandpa_porch.png",
    description: "따뜻한 햇살이 드는 할아버지의 마루",
  },

  // ===== BATTLE =====
  {
    id: "battle_arena",
    category: "battle",
    name: "버니 아레나 배경",
    price: 70,
    image: "/shop/backgrounds/battle/arena.png",
    description: "용감한 토끼들의 전투 경기장",
  },
  {
    id: "battle_castle_courtyard",
    category: "battle",
    name: "성 안뜰 배경",
    price: 70,
    image: "/shop/backgrounds/battle/castle_courtyard.png",
    description: "기사가 훈련하는 성의 안뜰",
  },
  {
    id: "battle_archery_range",
    category: "battle",
    name: "활쏘기 훈련장 배경",
    price: 70,
    image: "/shop/backgrounds/battle/archery_range.png",
    description: "숲속의 조용한 활쏘기 훈련장",
  },
  {
    id: "battle_battlefield",
    category: "battle",
    name: "전장 배경",
    price: 70,
    image: "/shop/backgrounds/battle/battlefield.png",
    description: "영웅이 나타나는 치열한 전장",
  },
  {
    id: "battle_dojo",
    category: "battle",
    name: "닌자 도장 배경",
    price: 70,
    image: "/shop/backgrounds/battle/dojo.png",
    description: "그림자처럼 조용한 닌자 도장",
  },
  {
    id: "battle_stable",
    category: "battle",
    name: "기마대 마구간 배경",
    price: 70,
    image: "/shop/backgrounds/battle/stable.png",
    description: "용맹한 기마대의 마구간",
  },
  {
    id: "battle_dragon_mountain",
    category: "battle",
    name: "용의 산 배경",
    price: 70,
    image: "/shop/backgrounds/battle/dragon_mountain.png",
    description: "전설의 용이 사는 산",
  },

  // ===== FANTASY =====
  {
    id: "fantasy_magic_castle",
    category: "fantasy",
    name: "마법의 성 배경",
    price: 80,
    image: "/shop/backgrounds/fantasy/magic_castle.png",
    description: "별빛 가득한 신비로운 마법 세계",
  },
  {
    id: "fantasy_wizard_tower",
    category: "fantasy",
    name: "마법사의 탑 배경",
    price: 80,
    image: "/shop/backgrounds/fantasy/wizard_tower.png",
    description: "신비로운 마법이 흐르는 탑",
  },
  {
    id: "fantasy_enchanted_forest",
    category: "fantasy",
    name: "요정의 숲 배경",
    price: 80,
    image: "/shop/backgrounds/fantasy/enchanted_forest.png",
    description: "작은 요정들이 사는 신비한 숲",
  },
  {
    id: "fantasy_dwarf_workshop",
    category: "fantasy",
    name: "드워프 공방 배경",
    price: 80,
    image: "/shop/backgrounds/fantasy/dwarf_workshop.png",
    description: "망치질 소리가 울리는 드워프의 공방",
  },
  {
    id: "fantasy_elf_village",
    category: "fantasy",
    name: "엘프 마을 배경",
    price: 80,
    image: "/shop/backgrounds/fantasy/elf_village.png",
    description: "나무 위에 자리한 엘프들의 마을",
  },
  {
    id: "fantasy_heavenly_clouds",
    category: "fantasy",
    name: "천상의 구름 배경",
    price: 80,
    image: "/shop/backgrounds/fantasy/heavenly_clouds.png",
    description: "포근한 구름 위 천사들의 세계",
  },
  {
    id: "fantasy_dark_castle",
    category: "fantasy",
    name: "어둠의 성 배경",
    price: 80,
    image: "/shop/backgrounds/fantasy/dark_castle.png",
    description: "어둠의 마법이 감도는 신비한 성",
  },
];