export type BookStory = {
  slug: string;
  title: string;
  image: string;
  sentences: string[];
};

export type BookLevel = {
  level: string;
  title: string;
  description: string;
  image: string;
  colorClass: string;
  stories: BookStory[];
};

const makeSlug = (title: string) => title.toLowerCase().replaceAll(" ", "-");

// 문장을 레벨별 공통 템플릿으로 자동 생성하던 이전 방식(makeStories)을 없애고,
// 스토리마다 실제로 다른 문장/문장 구조/이야기 결을 직접 작성한다.
// story()는 slug/image 경로만 자동으로 계산해주는 얇은 헬퍼.
const story = (level: string, title: string, sentences: string[]): BookStory => {
  const slug = makeSlug(title);
  return {
    slug,
    title,
    image: `/book/${level}/${slug}.png`,
    sentences,
  };
};

export const bookLevels: BookLevel[] = [
  {
    level: "level1",
    title: "Level 1",
    description: "First Words",
    image: "/book/book_level1.png",
    colorClass: "green",
    stories: [
      story("level1", "Cat", ["Cat.", "The cat is soft."]),
      story("level1", "Dog", ["Dog.", "Can the dog run fast?"]),
      story("level1", "Pig", ["Pig.", "The pig says oink!"]),
      story("level1", "Sun", ["Sun.", "Look at the sun!"]),
      story("level1", "Hat", ["Hat.", "Is this your hat?"]),
      story("level1", "Bag", ["Bag.", "My bag is heavy."]),
      story("level1", "Cup", ["Cup.", "The cup is full."]),
      story("level1", "Pen", ["Pen.", "Where is my pen?"]),
      story("level1", "Book", ["Book.", "I love this book!"]),
      story("level1", "Ball", ["Ball.", "The ball rolls away."]),
      story("level1", "Fish", ["Fish.", "Look, a fish!"]),
      story("level1", "Milk", ["Milk.", "The milk is cold."]),
      story("level1", "Cake", ["Cake.", "Do you like cake?"]),
      story("level1", "Apple", ["Apple.", "The apple fell down."]),
      story("level1", "Car", ["Car.", "Vroom! The car goes fast."]),
      story("level1", "Bus", ["Bus.", "Here comes the bus!"]),
      story("level1", "Box", ["Box.", "What is in the box?"]),
      story("level1", "Toy", ["Toy.", "This toy is mine."]),
      story("level1", "Bed", ["Bed.", "Time for bed!"]),
      story("level1", "Chair", ["Chair.", "Sit on the chair."]),
      story("level1", "Tree", ["Tree.", "Birds live in the tree."]),
      story("level1", "Flower", ["Flower.", "Smell the flower."]),
      story("level1", "Moon", ["Moon.", "Good night, moon!"]),
      story("level1", "Star", ["Star.", "Wish on a star."]),
      story("level1", "Rain", ["Rain.", "I hear the rain."]),
      story("level1", "Snow", ["Snow.", "Snow is cold and white."]),
      story("level1", "Egg", ["Egg.", "Crack the egg."]),
      story("level1", "Jam", ["Jam.", "Yum, I love jam!"]),
      story("level1", "Map", ["Map.", "Where does the map lead?"]),
      story("level1", "Run", ["Run.", "Run, run, run!"]),
    ],
  },
  {
    level: "level2",
    title: "Level 2",
    description: "Simple Sentences",
    image: "/book/book_level2.png",
    colorClass: "yellow",
    stories: [
      story("level2", "My Cat", ["This is my cat.", "She naps in the sun.", "I love my cat."]),
      story("level2", "My Dog", ["Woof! Here comes my dog.", "He wags his tail at me.", "We play every day."]),
      story("level2", "My Bag", ["Where is my bag?", "Oh, it's on the chair.", "I pack it for school."]),
      story("level2", "My Book", ["I found my favorite book.", "It has a dragon on the cover.", "I can't wait to read it."]),
      story("level2", "My Toy", ["My toy robot beeps.", "It walks across the floor.", "I laugh every time."]),
      story("level2", "My Ball", ["Bounce, bounce goes my ball!", "It rolls under the bed.", "I chase it and laugh."]),
      story("level2", "I See a Fish", ["I see a fish in the tank.", "It swims round and round.", "Its scales shine like gold."]),
      story("level2", "I Like Milk", ["I like cold milk.", "I drink it with breakfast.", "It makes my bones strong."]),
      story("level2", "I Eat Cake", ["Today I eat cake.", "It is my birthday!", "The frosting is pink and sweet."]),
      story("level2", "I Ride a Bus", ["I wait for the bus.", "It stops right in front of me.", "I wave to the driver."]),
      story("level2", "This Is My Hat", ["This is my hat.", "The wind almost blows it away!", "I hold it tight."]),
      story("level2", "This Is My Pen", ["Is this pen blue or black?", "I write my name with it.", "It is my favorite color."]),
      story("level2", "This Is My Bed", ["My bed has soft blankets.", "I hop in at night.", "I sleep like a bear."]),
      story("level2", "This Is My Cup", ["My cup has stars on it.", "I fill it with juice.", "Clink! I tap it with my spoon."]),
      story("level2", "The Sun Is Up", ["The sun is up!", "It peeks through my window.", "Time to start the day."]),
      story("level2", "The Moon Is Bright", ["The moon is bright tonight.", "It follows me on my walk.", "I say good night to it."]),
      story("level2", "A Red Apple", ["I hold a red apple.", "It is shiny and round.", "Crunch! I take a big bite."]),
      story("level2", "A Big Box", ["A big box sits by the door.", "Who could it be from?", "I open it with excitement."]),
      story("level2", "A Small Egg", ["A small egg sits in the nest.", "It is warm to touch.", "Soon a chick will hatch."]),
      story("level2", "A Green Tree", ["A green tree stands in my yard.", "Squirrels climb up and down.", "I like to sit under it."]),
      story("level2", "I Can Run", ["Watch me run!", "My legs move so fast.", "I feel like the wind."]),
      story("level2", "I Can Jump", ["I can jump really high.", "One, two, three, jump!", "I try to touch the sky."]),
      story("level2", "I Can Sit", ["I sit very still.", "I listen to the story.", "Then I sit up straight."]),
      story("level2", "I Can Play", ["Let's play together!", "I share my toys with friends.", "Playing makes the day fun."]),
      story("level2", "My Chair", ["This chair is just my size.", "I sit here every morning.", "It creaks a little when I move."]),
      story("level2", "My Map", ["I unfold my little map.", "It shows rivers and mountains.", "Someday I will explore it all."]),
      story("level2", "My Jam", ["My jam is sticky and sweet.", "I spread it on warm toast.", "A little gets on my nose."]),
      story("level2", "My Flower", ["My flower opened this morning.", "Its petals are bright pink.", "I water it with care."]),
      story("level2", "My Star", ["My star glows in the dark.", "I hung it above my bed.", "It watches over me at night."]),
      story("level2", "My Home", ["My home smells like cookies.", "The lights are warm and cozy.", "I am always happy here."]),
    ],
  },
  {
    level: "level3",
    title: "Level 3",
    description: "Daily Life",
    image: "/book/book_level3.png",
    colorClass: "pink",
    stories: [
      story("level3", "My Morning", ["Ring! My alarm wakes me up.", "I stretch and yawn big.", "I get dressed quickly.", "Then I run downstairs for breakfast."]),
      story("level3", "At Home", ["Home is where I feel safe.", "My dog greets me at the door.", "We eat dinner around the table.", "I hug my family before bed."]),
      story("level3", "At School", ["The school bell rings loudly.", "I find my seat by the window.", "My teacher says good morning.", "I raise my hand to answer."]),
      story("level3", "My Friend", ["My friend waves from across the yard.", "We build a fort out of blocks.", "Sometimes we argue, then we laugh.", "Friends make everything more fun."]),
      story("level3", "My Family", ["My family is big and loud.", "Grandpa tells the best jokes.", "My sister always wins at games.", "I would not trade them for anything."]),
      story("level3", "Lunch Time", ["The lunch bell finally rings.", "I trade my apple for cookies.", "My friends and I talk and laugh.", "Then it's back to class we go."]),
      story("level3", "Play Time", ["Recess! Everyone runs outside.", "I climb to the top of the slide.", "My friends chase me around the yard.", "The whistle blows too soon."]),
      story("level3", "Reading Time", ["The room grows quiet and still.", "I find a cozy corner to sit.", "The story pulls me into another world.", "I almost forget where I am."]),
      story("level3", "My Room", ["My room is painted sky blue.", "Stickers cover half of my wall.", "My stuffed animals sit in a row.", "This little room is all mine."]),
      story("level3", "My Desk", ["My desk has a wobbly leg.", "Pencils and crayons fill the drawer.", "I doodle in the corner of my paper.", "It is where I do my best thinking."]),
      story("level3", "My Teacher", ["My teacher always has a kind smile.", "She never gets tired of my questions.", "She claps when I get something right.", "I want to make her proud."]),
      story("level3", "My Class", ["Twenty of us sit in a circle.", "We take turns sharing our stories.", "Someone always makes the class laugh.", "I like being part of this group."]),
      story("level3", "My Pet", ["My pet hides when visitors come.", "But with me, it is brave.", "It follows me from room to room.", "We are the best of friends."]),
      story("level3", "My Shoes", ["My shoes squeak on the floor.", "One lace is always coming undone.", "I race in them at recess.", "They are covered in scuffs and stories."]),
      story("level3", "My Bike", ["My bike used to have training wheels.", "Now I ride it all by myself.", "The wind rushes past my ears.", "I feel free when I ride."]),
      story("level3", "A Rainy Day", ["Drip, drop, the rain falls down.", "I press my nose to the window.", "Maybe today I'll stay in and draw.", "Rainy days have their own kind of magic."]),
      story("level3", "A Sunny Day", ["Not a cloud in the sky today.", "I grab my hat and head outside.", "The grass feels warm under my feet.", "Sunny days are made for adventures."]),
      story("level3", "A Snowy Day", ["Everything outside turns soft and white.", "I bundle up in my warmest coat.", "My boots crunch with every step.", "I catch snowflakes on my tongue."]),
      story("level3", "Going Home", ["The last bell means it's time to go.", "I gather my things and say goodbye.", "The walk home feels shorter every day.", "I can't wait to tell everyone about school."]),
      story("level3", "Going Outside", ["The fresh air calls my name.", "I leave my shoes by the door.", "The grass tickles my bare feet.", "Outside always feels like an adventure."]),
      story("level3", "Clean Up", ["Toys are scattered all across the floor.", "One by one, I put them away.", "It takes longer than I think it will.", "But my tidy room feels so much better."]),
      story("level3", "Snack Time", ["My stomach starts to grumble.", "I pick crackers and a juice box.", "I share a few with my friend.", "Snacks make the afternoon feel shorter."]),
      story("level3", "Bath Time", ["Bubbles pile high in the tub.", "I make a hat out of foam.", "The warm water makes me sleepy.", "Clean and cozy, I hop into bed."]),
      story("level3", "Bed Time", ["The stars come out one by one.", "I brush my teeth and climb into bed.", "Mom reads just one more story.", "My eyes grow heavy before it ends."]),
      story("level3", "The Park", ["Swings creak back and forth in the wind.", "I dare myself to go higher.", "A dog chases a ball nearby.", "I never want to leave the park."]),
      story("level3", "The Library", ["Shhh, the library asks for quiet.", "Shelves of books stretch to the ceiling.", "I pick three to take home.", "The librarian stamps my card with a smile."]),
      story("level3", "The Bus Stop", ["I check the clock again and again.", "Finally, the bus rounds the corner.", "I climb the big steps carefully.", "My favorite seat is always by the window."]),
      story("level3", "The Playground", ["Kids run in every direction.", "I race my friend to the slide.", "We take turns on the monkey bars.", "Time always flies at the playground."]),
      story("level3", "My Birthday", ["Balloons hang from every corner.", "I blow out all my candles at once.", "My friends sing a little off key.", "It is the best day of the year."]),
      story("level3", "My Picture", ["I dip my brush in bright yellow.", "A sun takes shape on the paper.", "I add clouds and a smiling face.", "I hang it proudly on the fridge."]),
    ],
  },
  {
    level: "level4",
    title: "Level 4",
    description: "Fun Activities",
    image: "/book/book_level4.png",
    colorClass: "blue",
    stories: [
      story("level4", "Playing Soccer", ["The whistle blows to start the game.", "I chase the ball down the field.", "My foot connects — goal!", "My team lifts me up cheering.", "Soccer days are the best days."]),
      story("level4", "Riding a Bike", ["Wind rushes past as I pedal fast.", "I ring my bell at every corner.", "A puddle splashes under my tire.", "I laugh and pedal even faster.", "By the time I stop, I'm out of breath."]),
      story("level4", "Drawing Pictures", ["Blank paper waits in front of me.", "I choose blue for the sky first.", "Slowly a whole world appears.", "My sister asks what I'm drawing.", "\"A dragon,\" I say with a grin."]),
      story("level4", "Making Cookies", ["Flour dusts the counter like snow.", "I crack the egg — a little messy.", "We roll the dough into little balls.", "The oven fills the kitchen with warmth.", "The first bite is always the best."]),
      story("level4", "Flying a Kite", ["My kite dips, then catches the wind.", "Higher and higher it climbs.", "I run to keep it in the air.", "For a moment, it looks like it's dancing.", "I never want to reel it back in."]),
      story("level4", "Jumping Rope", ["Slap, slap goes the rope on the ground.", "I count each jump under my breath.", "Twenty, twenty-one, twenty-two!", "My legs start to feel tired.", "I stop, laughing and out of breath."]),
      story("level4", "Going Camping", ["We pitch the tent as the sun sets.", "A fire crackles and pops nearby.", "Marshmallows turn golden on our sticks.", "An owl hoots somewhere in the dark.", "I fall asleep listening to the crickets."]),
      story("level4", "Making a Sandcastle", ["Wet sand packs perfectly into my bucket.", "I flip it over — a perfect tower!", "Shells become windows and doors.", "A wave creeps closer and closer.", "Splash! My castle returns to the sea."]),
      story("level4", "Swimming Day", ["Cold water shocks me at first.", "Then I dive under and swim like a fish.", "My friend splashes me from behind.", "We race to the other side.", "I climb out, dripping and happy."]),
      story("level4", "Picnic Day", ["We spread a checkered blanket on the grass.", "Ants march past looking for crumbs.", "I bite into a sandwich under the shade.", "A bee buzzes a little too close.", "We laugh and pack up before it lands."]),
      story("level4", "Music Class", ["Boom, boom go the drums today.", "My teacher taps out a rhythm.", "I try to copy it exactly.", "Everyone joins in, a little off beat.", "Together we sound like a real band."]),
      story("level4", "Dance Time", ["The music starts and my feet just move.", "I spin until the room blurs.", "My friend copies my silly moves.", "We invent a dance with no name.", "By the end, we can't stop laughing."]),
      story("level4", "Planting Seeds", ["I poke a hole in the soft dirt.", "One tiny seed drops in.", "I cover it and give it water.", "Every day I check for green.", "One morning, a little sprout appears!"]),
      story("level4", "Feeding the Fish", ["I tap a little food onto the water.", "Fish dart up from every corner.", "One brave fish nibbles right at the top.", "I count them as they swim.", "They circle back, hoping for more."]),
      story("level4", "Building Blocks", ["Block by block, my tower grows.", "It wobbles a little at the top.", "I hold my breath and add one more.", "Crash! Down it all comes.", "I laugh and start building again."]),
      story("level4", "Painting Day", ["My brush drips blue onto the paper.", "I mix in yellow — now it's green!", "Paint splatters on my hands too.", "My picture doesn't look like anything real.", "But I love it anyway."]),
      story("level4", "Treasure Hunt", ["An old map leads the way.", "X marks a spot behind the tree.", "We dig carefully in the soft dirt.", "Clink! Something metal hits the shovel.", "A small box full of coins appears!"]),
      story("level4", "Bubble Play", ["I dip the wand and blow gently.", "A giant bubble wobbles into the air.", "It catches the sunlight like glass.", "I chase it before it can pop.", "Pop! It vanishes, and I laugh."]),
      story("level4", "Water Play", ["Squirt! Cold water hits my arm.", "I fire back with my water gun.", "We chase each other around the yard.", "Everyone ends up soaked head to toe.", "It's the perfect way to cool off."]),
      story("level4", "Toy Shop", ["Shelves are packed with toys of every kind.", "A wind-up robot walks right off the shelf.", "I pick it up and it beeps happily.", "The shopkeeper winks and wraps it up.", "I can't wait to try it at home."]),
      story("level4", "Puzzle Time", ["Five hundred tiny pieces cover the table.", "I search for a matching edge.", "One piece, then another, clicks into place.", "The picture slowly starts to make sense.", "The very last piece is the best feeling."]),
      story("level4", "Making a Card", ["I fold the paper carefully in half.", "A heart takes shape under my scissors.", "I write \"I love you\" inside.", "Glitter sticks to everything, even my nose.", "I can't wait to give it away."]),
      story("level4", "Visiting Grandma", ["Her porch light is always on for me.", "She wraps me in a big warm hug.", "The kitchen smells like fresh bread.", "She tells the same funny story again.", "I laugh like it's the first time."]),
      story("level4", "Helping Mom", ["Dishes clink as I dry each one.", "I carry the heavy bags without spilling.", "Mom hums while we work together.", "\"Thank you, my little helper,\" she says.", "I stand a little taller after that."]),
      story("level4", "Helping Dad", ["The wrench is almost too heavy to hold.", "I hand Dad each tool he needs.", "Grease smudges across both our hands.", "Together we fix the squeaky chair.", "Dad ruffles my hair and says thanks."]),
      story("level4", "Cleaning My Room", ["Clothes and toys cover every inch of floor.", "One pile becomes two, then none.", "I find a toy I forgot I had.", "My bed finally has a smooth blanket.", "The room feels bigger when it's clean."]),
      story("level4", "Cooking Soup", ["The pot bubbles and steams on the stove.", "I stir slowly, careful not to splash.", "Carrots and potatoes swim in the broth.", "A taste test — needs a little more salt.", "We slurp it up together at dinner."]),
      story("level4", "Taking Photos", ["Click! I catch a bird mid-flight.", "I crouch low for the perfect angle.", "My dog refuses to sit still.", "Finally, a photo where everyone is smiling.", "I can't wait to print it out."]),
      story("level4", "Reading with Bunny", ["Bunny points at a picture and squeaks.", "I read the words slowly out loud.", "\"What happens next?\" Bunny seems to ask.", "We turn the page together.", "The story ends, but Bunny wants another."]),
      story("level4", "Game Day", ["Dice roll across the table.", "\"Six! I get to move ahead!\"", "My friend groans and laughs at once.", "We trade the lead back and forth.", "Whoever wins, we always play again."]),
    ],
  },
  {
    level: "level5",
    title: "Level 5",
    description: "Adventure Stories",
    image: "/book/book_level5.png",
    colorClass: "purple",
    stories: [
      story("level5", "The Little Map", ["Bunny finds an old map tucked in a drawer.", "The lines lead through a tangled forest.", "She packs a snack and sets off alone.", "Twice she takes a wrong turn.", "At last, the path opens into a hidden meadow.", "Bunny sits down, amazed she found it herself."]),
      story("level5", "The Lost Bag", ["Bunny realizes her bag is missing.", "She retraces her steps through the park.", "A fox trots up holding it in his mouth.", "\"Is this yours?\" he asks with a grin.", "Bunny laughs — she must have dropped it running.", "She thanks the fox and offers him a carrot."]),
      story("level5", "The Big Hill", ["The hill looks impossibly steep from below.", "Bunny's legs ache halfway up.", "She almost turns back twice.", "One more push, and she reaches the top.", "The whole valley spreads out beneath her.", "She sits and catches her breath, grinning."]),
      story("level5", "The Forest Path", ["A narrow path winds through the tall trees.", "An owl watches silently from a branch.", "\"Where does this path go?\" Bunny wonders aloud.", "\"Further than you think,\" the owl replies.", "She keeps walking, curious now more than ever.", "The path ends at a quiet, sparkling pond."]),
      story("level5", "The Blue Boat", ["A small blue boat bobs by the dock.", "Bunny climbs in, a little nervous.", "The current carries her gently downstream.", "Fish flicker beneath the clear water.", "For a while, she just watches and listens.", "She paddles back before the sun sets."]),
      story("level5", "The Train Ride", ["Bunny hops aboard just as the doors close.", "A mole is already asleep in the seat.", "He wakes with a start and yelps.", "They both laugh at the surprise.", "He shows her his favorite window view.", "They wave goodbye at very different stops."]),
      story("level5", "The Airport Day", ["Planes roar and lift into the clouds.", "Bunny presses her nose to the glass.", "She imagines where each one is going.", "A voice calls a flight to somewhere far away.", "She squeezes her ticket tightly in her paw.", "Soon, it will be her turn to fly."]),
      story("level5", "The Secret Door", ["A door is hidden behind the ivy wall.", "Bunny tugs, but it won't budge.", "Bear leans his weight against it too.", "Creak! It finally swings open.", "Inside is a garden no one has seen in years.", "They agree to keep it their secret."]),
      story("level5", "The Tiny Key", ["A tiny key glints in the grass.", "Bunny wonders what it could possibly open.", "She tries it on every door in the house.", "None of them fit — until the old chest.", "Click! The lid pops open at last.", "Inside are letters from long ago."]),
      story("level5", "The Magic Garden", ["The garden hums with an odd little tune.", "Bunny leans in close to listen.", "The flowers seem to hum back to her.", "Bear laughs and joins the strange chorus.", "Soon they are both humming and dancing.", "The garden glows brighter with every note."]),
      story("level5", "The Brave Bunny", ["A rustling sound comes from the bushes at night.", "Bunny's heart pounds in her chest.", "She grips her flashlight and steps closer.", "A tiny kitten blinks up at her.", "She laughs, relieved, and scoops it up gently.", "She walks home feeling braver than before."]),
      story("level5", "The Friendly Bear", ["Bunny freezes when she sees the bear.", "He waves and says a friendly hello.", "She relaxes and waves back shyly.", "They share berries and swap stories.", "By sunset, the fear is completely gone.", "She skips home with a brand new friend."]),
      story("level5", "The Night Walk", ["The town sleeps under a blanket of stars.", "Bunny tiptoes outside, just to look.", "An owl glides silently overhead.", "\"Can't sleep either?\" it seems to ask.", "They sit together under the moonlight.", "Bunny finally feels sleepy and heads inside."]),
      story("level5", "The Rainbow Bridge", ["Rain stops, and color spills across the sky.", "Bunny gasps at the giant arch of light.", "She races to where it seems to touch the ground.", "It always stays just out of reach.", "She laughs at her own silly chase.", "The colors fade, but the memory doesn't."]),
      story("level5", "The Cloud Trip", ["Bunny lies back in the soft green grass.", "A fluffy cloud drifts slowly overhead.", "She imagines climbing right up onto it.", "From up there, the whole world looks tiny.", "She waves down at her own front door.", "A gentle breeze brings her back to reality."]),
      story("level5", "The River Stone", ["A smooth gray stone catches Bunny's eye.", "She skips it once across the river.", "It bounces three times before it sinks.", "\"My turn!\" Bear says, grabbing a stone.", "His splashes far more than it skips.", "They laugh and try again and again."]),
      story("level5", "The Hidden Box", ["Something metal glints beneath the fallen leaves.", "Bunny brushes away the dirt carefully.", "It's an old tin box, rusted at the edges.", "Inside are faded photographs of a family.", "She wonders who they were, long ago.", "She tucks the box away, safe and sound."]),
      story("level5", "The Tall Tower", ["Stone stairs spiral up into the clouds.", "Bunny counts each step as she climbs.", "Halfway up, her legs start to burn.", "Bear catches up, breathing just as hard.", "Together they reach the very top.", "The view makes every step worth it."]),
      story("level5", "The Windy Road", ["The wind nearly knocks Bunny off her feet.", "Her ears flap like little flags.", "Leaves swirl in circles all around her.", "She holds tight to her wobbling hat.", "For a moment, it feels like flying.", "She reaches home laughing and windswept."]),
      story("level5", "The Star Ticket", ["A ticket shaped like a star falls at her feet.", "It reads: good for exactly one wish.", "Bunny thinks carefully — what does she truly want?", "She wishes for one more day like today.", "The ticket glows warm in her hand.", "She keeps it tucked safely in her pocket."]),
      story("level5", "The Quiet Cave", ["A dark opening waits at the base of the hill.", "Bunny steps in, her voice echoing softly.", "Tiny crystals sparkle along the walls.", "An owl lights the way with a small lantern.", "Their footsteps are the only sound.", "They leave, promising to return someday."]),
      story("level5", "The Happy Camp", ["Tents rise as the sky turns orange.", "A fire crackles between the two friends.", "Marshmallows turn golden, then a little too dark.", "Stars blink on, one by one.", "They hum a quiet song together.", "Bunny falls asleep before the fire dies down."]),
      story("level5", "The Ocean Walk", ["Waves hiss and pull back along the shore.", "Bunny hunts for shells among the foam.", "A crab scuttles sideways and disappears.", "She holds a shiny shell up to the light.", "The sunset turns the whole sky pink.", "She walks home with pockets full of treasures."]),
      story("level5", "The Mountain Hat", ["Snow crunches under every careful step.", "Bunny pulls her hat down against the wind.", "The path grows steeper the higher they climb.", "Bear's breath puffs like little clouds.", "At the peak, the whole world spreads white below them.", "They cheer, their voices echoing far away."]),
      story("level5", "The Green Island", ["Palm trees sway above the quiet shore.", "Bunny wades into the warm, clear water.", "Colorful fish dart around her feet.", "She finds a shady spot to rest.", "A parrot squawks somewhere in the trees.", "She could stay on this island forever."]),
      story("level5", "The Small Lighthouse", ["The lighthouse beam sweeps across the dark water.", "Bunny climbs the spiral stairs to the top.", "Bear waits below, watching the boats.", "The light guides a small fishing boat safely home.", "Bunny waves as it passes below.", "She feels proud to help, even in a small way."]),
      story("level5", "The Sunny Farm", ["Chickens scatter as Bunny scoops out their feed.", "A rooster crows louder than she expects.", "She pets a sheep with the softest wool.", "A basket of warm eggs waits by the barn.", "She carries it carefully back to the house.", "Farm mornings always start the day off right."]),
      story("level5", "The Busy Market", ["Stalls overflow with fruit, bread, and flowers.", "A vendor offers Bunny a taste of berries.", "Bear insists on carrying the heaviest basket.", "They haggle playfully over the price of apples.", "By the end, their basket is nearly overflowing.", "They walk home already planning next week's list."]),
      story("level5", "The Long Train", ["The train rattles past fields turning gold.", "Bunny presses her face to the cool window.", "Mountains rise, then fade behind her.", "A stranger across the aisle offers a friendly nod.", "Hours pass before the train finally slows.", "She steps off, ready for whatever comes next."]),
      story("level5", "The New Town", ["Bunny's new street is full of unfamiliar faces.", "Bear shows up with a warm loaf of bread.", "\"Welcome,\" he says, \"I live just around the corner.\"", "They walk together, and he points out his favorite shop.", "By evening, the town already feels a little less strange.", "Bunny falls asleep glad she isn't alone."]),
    ],
  },
  {
    level: "level6",
    title: "Level 6",
    description: "Longer Stories",
    image: "/book/book_level6.png",
    colorClass: "mint",
    stories: [
      story("level6", "Bunny and the Moon", ["The moon hangs low and orange over the hill.", "Bunny has never seen it look so close.", "She wonders if it's warm or cold up there.", "\"Maybe it's lonely,\" she says to herself.", "She waves, just in case it can see her.", "For a moment, she swears it glows a little brighter.", "She falls asleep still thinking about the moon."]),
      story("level6", "The Book Under the Tree", ["An old book lies forgotten beneath the roots.", "Its cover is faded, but the pages still turn.", "Bunny sits down right where she found it.", "Inside are maps of places she's never heard of.", "She traces the inked coastlines with her paw.", "The afternoon slips by without her noticing.", "She tucks the book under her arm to keep."]),
      story("level6", "The Cat by the Window", ["A cat appears on the windowsill one morning.", "It watches Bunny with sleepy, curious eyes.", "She sets out a small bowl of milk.", "The cat sniffs, then drinks it slowly.", "The next day, it's there again, waiting.", "Soon it's a part of her morning routine.", "Bunny never learns its name, but doesn't mind."]),
      story("level6", "The Long Rainy Day", ["Rain drums steadily against the roof all day.", "Outside plans are cancelled before they start.", "Bunny builds a fort from every blanket she owns.", "She reads by flashlight inside her small hideout.", "Thunder rumbles, but the fort feels safe.", "By evening, the rain has softened to a whisper.", "She decides rainy days aren't so bad after all."]),
      story("level6", "The Quiet Night", ["The whole town seems to hold its breath.", "Bunny sits on her porch, wrapped in a blanket.", "Crickets hum somewhere in the tall grass.", "One star, then dozens, appear overhead.", "She doesn't say a word, just watches.", "The quiet feels like its own kind of music.", "She goes inside only when her eyes grow heavy."]),
      story("level6", "The Little Helper", ["Dishes pile high after a busy dinner.", "Bunny rolls up her sleeves without being asked.", "Soap bubbles float up and pop on her nose.", "Mom notices and raises an eyebrow, surprised.", "\"Look at you,\" she says, smiling.", "Bunny stands a little taller at the compliment.", "She decides to make helping a habit."]),
      story("level6", "The Best Present", ["Bear's birthday is only two days away.", "Bunny has no money for a store-bought gift.", "She spends an evening folding paper into shapes.", "A card unfolds into a tiny paper garden.", "Bear's eyes widen when he opens it.", "\"This is better than anything you could buy,\" he says.", "Bunny beams the whole walk home."]),
      story("level6", "The Warm Scarf", ["Wind bites harder with each passing day.", "Bunny notices Bear shivering at the bus stop.", "She spends every evening knitting in secret.", "Some rows come out crooked, but she keeps going.", "On the coldest morning, she hands it over.", "Bear wraps it around his neck immediately.", "\"Perfect,\" he says, and means it."]),
      story("level6", "The New Neighbor", ["Boxes pile up outside the house next door.", "A small rabbit peeks out, looking unsure.", "Bunny waves first, even though she feels shy too.", "\"Want to see the best climbing tree around?\" she asks.", "The new rabbit's face lights up.", "By dinnertime, they've already made up a secret code.", "Bunny is glad she said hello first."]),
      story("level6", "The Missing Carrot", ["Bunny's favorite carrot has vanished from the counter.", "She checks the fridge, the drawer, even her pockets.", "She retraces her whole morning, step by step.", "Behind the garden gate, she spots something orange.", "It's exactly where she'd left it the day before.", "She laughs at herself for forgetting.", "The carrot tastes even better after the search."]),
      story("level6", "The Sleepy Bear", ["Bear's eyes droop halfway through the story.", "\"I want to hear the end,\" he mumbles.", "Bunny reads a little softer, a little slower.", "His breathing evens out before the last page.", "She sets the book gently on the shelf.", "A blanket is pulled up over his shoulders.", "The lamp clicks off, and the room goes quiet."]),
      story("level6", "The Kind Frog", ["A small frog sits alone by the pond's edge.", "Bunny asks why he looks so glum.", "\"I forgot the words to my favorite song,\" he says.", "She hums the first few notes she remembers.", "His eyes light up — that's it exactly!", "Together they sing it all the way through.", "The pond seems to ripple along with the tune."]),
      story("level6", "The Small Promise", ["\"I'll visit every Friday,\" Bunny tells Bear.", "The first week, she brings a basket of berries.", "The next, they build a blanket fort together.", "Some weeks she almost forgets, but never does.", "Bear starts marking Fridays on his calendar.", "Months later, the promise still holds true.", "Small promises, it turns out, can matter the most."]),
      story("level6", "The Big Question", ["\"Why is the sky blue?\" Bunny asks one day.", "Her teacher pulls out a picture of sunlight.", "\"Light bends and scatters,\" she explains simply.", "Bunny nods, though she still has more questions.", "\"Why does it turn orange at sunset then?\"", "Her teacher laughs, \"That's tomorrow's lesson.\"", "Bunny can't wait for tomorrow to come."]),
      story("level6", "The Starry Room", ["Paper stars hang crooked across Bunny's ceiling.", "Each one took an entire evening to cut.", "At night, the lamp makes them glow softly.", "She names a memory for every single star.", "One is her first bike ride, wobbly and proud.", "Another is a rainy picnic that turned out perfect.", "She falls asleep beneath her own little sky."]),
      story("level6", "The Letter from Friend", ["An envelope with unfamiliar handwriting arrives.", "Bunny recognizes it — her old friend, from far away.", "He writes about his new school and a lost tooth.", "She reads it twice before writing back.", "Her reply fills three whole pages.", "She adds a drawing of her favorite tree.", "Mailing it feels like sending a piece of home."]),
      story("level6", "The Secret Picnic", ["Bunny packs sandwiches into a woven basket.", "She picks the quietest spot under the oldest tree.", "When Bear arrives, he stops mid-step, surprised.", "\"You did all this?\" he asks, grinning.", "They spread the blanket and share every bite.", "A bird lands nearby, hoping for crumbs.", "It becomes the spot they return to all summer."]),
      story("level6", "The Winter Story", ["The first snowfall blankets the whole town overnight.", "Bunny and Bear race outside before breakfast.", "A lopsided snowman takes shape between them.", "A carrot becomes a nose; two stones, eyes.", "Cocoa warms their paws when they finally head in.", "Snowflakes melt slowly on the windowsill.", "They agree it's the best snow day yet."]),
      story("level6", "The Summer Story", ["Heat shimmers above the road by midday.", "Bunny and Bear race each other to the river.", "Cold water is a relief the moment they jump in.", "Watermelon juice drips down their chins afterward.", "Fireflies blink on as the sky turns purple.", "They chase the tiny lights until it's fully dark.", "Summer nights never seem to want to end."]),
      story("level6", "The Spring Flower", ["A single seed goes into the soft spring dirt.", "Bunny checks on it every single morning.", "Nothing happens for what feels like forever.", "Then one day, a tiny green shoot appears.", "She waters it a little more carefully now.", "Weeks later, a bright flower finally opens.", "Patience, she learns, grows things too."]),
      story("level6", "The Autumn Leaves", ["Leaves turn gold, then red, almost overnight.", "Bunny rakes them into the biggest pile yet.", "Bear cannonballs in before she can stop him.", "Leaves fly everywhere, catching in both their ears.", "They rebuild the pile just to jump in again.", "By evening, the yard is a scattered mess.", "Neither of them minds raking it all tomorrow."]),
      story("level6", "The Long Walk Home", ["The final bell rings, and school lets out.", "Bunny takes the longer path through the woods.", "She stops to watch ducks paddle across the pond.", "A squirrel scolds her from somewhere overhead.", "The sun dips lower with every step.", "By the time she's home, the sky has turned pink.", "It was the best kind of slow afternoon."]),
      story("level6", "The Library Light", ["The library stays open later on Thursdays.", "Bunny finds her favorite corner already lit.", "Dust drifts gently through the lamp's soft glow.", "She loses track of time in her book.", "A librarian gently reminds her it's almost closing.", "She checks out one more, just in case.", "The walk home feels quiet and content."]),
      story("level6", "The Dream Train", ["In her dream, Bunny boards a train made of clouds.", "It climbs higher, past rooftops and treetops.", "Stars blink past the window like fireflies.", "The conductor tips his hat — it's Bear!", "They ride to a station shaped like a teacup.", "Everything there smells like cinnamon and sugar.", "She wakes up smiling, still tasting the dream."]),
      story("level6", "The Happy Mistake", ["Bunny grabs the wrong jar of paint by accident.", "Blue and yellow swirl together without her meaning to.", "She almost wipes it away, frustrated.", "But the green underneath catches the light just right.", "She adds it to the whole painting on purpose now.", "It becomes her favorite piece she's ever made.", "Some mistakes, she decides, are worth keeping."]),
      story("level6", "The Brave Choice", ["The tall slide looks taller from up close.", "Bunny's paws freeze on the top rung.", "Other kids zoom past her, laughing.", "She counts to three and lets go.", "Wind rushes past faster than she expected.", "She lands with a thump and a huge grin.", "She climbs right back up to do it again."]),
      story("level6", "The First Stage", ["Bunny's lines are memorized, but her stomach still flips.", "Bright lights make the audience hard to see.", "Her voice wobbles on the very first word.", "She takes a breath and finds her footing.", "By the last line, the words come easy.", "Applause fills the room louder than she expected.", "She takes a bow, cheeks warm with pride."]),
      story("level6", "The Last Cookie", ["One cookie sits alone on the plate.", "Both Bunny and Bear reach for it at once.", "They pause, then laugh at the same idea.", "She breaks it carefully down the middle.", "Somehow, half tastes just as good as whole.", "They talk long after the crumbs are gone.", "Sharing, they agree, makes it sweeter anyway."]),
      story("level6", "The Night Book", ["One page a night is Bunny's quiet rule.", "Tonight's chapter follows an explorer through a jungle.", "She pictures vines and hidden waterfalls as she reads.", "Her eyelids grow heavy before the chapter ends.", "She marks the page and turns off the lamp.", "The explorer's next move stays in her dreams.", "Tomorrow night, she'll find out what happens."]),
      story("level6", "The Good Memory", ["An old photo album sits open on her lap.", "Sunburnt cheeks and sandy toes fill every page.", "She remembers the sandcastle that took all afternoon.", "And the wave that knocked it down in seconds.", "She laughs quietly, tracing the edges of the photos.", "Some memories, she realizes, only get better with time.", "She closes the album and goes to make a new one."]),
    ],
  },
];

export function getBookLevel(level: string) {
  return bookLevels.find((item) => item.level === level);
}

export function getBookStory(level: string, story: string) {
  const currentLevel = getBookLevel(level);
  return currentLevel?.stories.find((item) => item.slug === story);
}
